# 开发配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 8080

#by zhengkai.blog.csdn.net
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
--- #--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: true
--- #--------------------redis配置---------------------------
spring:
    redis:
        host: 127.0.0.1 # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password:  # Redis服务器连接密码（默认为空）
        timeout: 1000ms # 连接超时时间（毫秒）