
@Base = localhost:8080
GET http://{{Base}}/user/test

### 获取公钥
GET http://{{Base}}/user/getPublicKy

### 加密
GET http://{{Base}}/user/encryption?str=fanhoufang

### 登录
POST http://{{Base}}/user/login
content-type: application/json

{
    "username": "www",
    "password": "q++S5ss/ShbYOunZY/ropOgZmxwdPrSeLsSeevefwktP4oU1+qf0Rl61/L4FXGxARU6GDCdWn7pSq9AeIj1FCQfG3nmW4m/aKwLAWlGBcxsg/PCauGd0LO74wmsvagH3+0zFRq2RuaV5PeL4dY9zfhRImuLxgoN5ojB2cHj67MnvCbk3TNeYBMlEQJihx5BOPCNNLjAmq84DavO8jXIIrs84gzeNB7ZXtPjuotyBnwyczNuaVvrdwnGgzrEEHrnzBQdZuxyhut++jKisBKMgqLG2XBoRnkSbR49iM4+dYuACgezNTzcXFZXOpowFApir8jc4IRMipFmm8rD4fAWlqg=="
}
###
GET http://{{Base}}/user/getUser
###
GET http://{{Base}}/user/getOne?userId=8
###
POST http://{{Base}}/user/register
content-type: application/json

{
    "username": "哇哇哇哇",
    "password": "5555555555"
}

###
POST http://{{Base}}/user/changePassword
content-type: application/json

{
    "userId": "6",
    "password": "32131123"
}